// packages/ui/react/src/button/button.tsx
"use client";

import { Button as Parts, mergeProps, type ButtonRootProps } from "@kimak/headless-react";
import { buttonAttrs, type ButtonSize, type ButtonVariant } from "./button-attrs";

export interface ButtonProps extends ButtonRootProps {
  variant?: ButtonVariant;
  size?: ButtonSize;
}

function ButtonField({ children, variant, size, ...props }: ButtonProps) {
  const look = buttonAttrs({ variant, size });

  return (
    <Parts.Root {...mergeProps(look, props)}>
      {children}
      <Parts.Indicator />
    </Parts.Root>
  );
}

export const Button = Object.assign(ButtonField, {
  Root: Parts.Root,
  Indicator: Parts.Indicator,
});

// packages/ui/svelte/src/button/button.svelte
<script lang="ts">
  import { Button, type ButtonRootProps } from "@kimak/headless-svelte";
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { buttonAttrs, type ButtonSize, type ButtonVariant } from "./button-attrs";

  export interface ButtonProps
    extends ButtonRootProps,
      Omit<HTMLButtonAttributes, keyof ButtonRootProps> {
    children?: Snippet;
    ref?: (node: HTMLElement | null) => void;
    variant?: ButtonVariant;
    size?: ButtonSize;
    href?: string;
  }

  let {
    children,
    ref: consumerRef,
    variant,
    size,
    ...props
  }: ButtonProps = $props();

  const look = $derived(buttonAttrs({ variant, size }));
</script>

<Button.Root {...look} {...props} ref={consumerRef}>
  {@render children?.()}
  <Button.Indicator />
</Button.Root>
